"""initial

Revision ID: 0c7cc2a37599
Revises:
Create Date: 2026-07-13 11:32:08.133787

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c7cc2a37599'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('email_addresses', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('slack_user_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('is_self', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threads',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SLACK', name='channel_type', create_constraint=True), nullable=False),
    sa.Column('external_thread_id', sa.String(length=255), nullable=True),
    sa.Column('participant_person_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('subject_or_topic', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threads_external_thread_id'), 'threads', ['external_thread_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SLACK', name='channel_type', create_constraint=True), nullable=False),
    sa.Column('external_message_id', sa.String(length=255), nullable=True),
    sa.Column('thread_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('sender_person_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('recipient_person_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('permalink', sa.String(length=2048), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sender_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_external_message_id'), 'messages', ['external_message_id'], unique=True)
    op.create_table('commitments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_message_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('thread_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('committer_person_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('recipient_person_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False),
    sa.Column('direction', sa.Enum('MADE_BY_USER', 'OWED_TO_USER', name='commitment_direction', create_constraint=True), nullable=False),
    sa.Column('raw_text_span', sa.Text(), nullable=False),
    sa.Column('commitment_type', sa.Enum('SIMPLE', 'DELEGATED', 'CONDITIONAL', 'RECURRING', name='commitment_type', create_constraint=True), nullable=False),
    sa.Column('raw_temporal_phrase', sa.String(length=500), nullable=True),
    sa.Column('resolved_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_confidence', sa.Float(), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'AT_RISK', 'OVERDUE', 'FULFILLED', 'RENEGOTIATED', 'DISMISSED', 'NEEDS_CLARIFICATION', name='commitment_status', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['committer_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eval_labels',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('message_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('is_commitment', sa.Boolean(), nullable=False),
    sa.Column('correct_committer', sa.String(length=255), nullable=True),
    sa.Column('correct_deadline', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_labels_message_id'), 'eval_labels', ['message_id'], unique=False)
    op.create_table('commitment_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('commitment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.Enum('EXTRACTED', 'RENEGOTIATED', 'FULFILLMENT_SIGNAL', 'CONFIRMED', 'DISMISSED', 'EDITED_SOURCE', 'RETRACTED_SOURCE', name='commitment_event_type', create_constraint=True), nullable=False),
    sa.Column('evidence_message_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['commitment_id'], ['commitments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commitment_events_commitment_id'), 'commitment_events', ['commitment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commitment_events_commitment_id'), table_name='commitment_events')
    op.drop_table('commitment_events')
    op.drop_index(op.f('ix_eval_labels_message_id'), table_name='eval_labels')
    op.drop_table('eval_labels')
    op.drop_table('commitments')
    op.drop_index(op.f('ix_messages_external_message_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_threads_external_thread_id'), table_name='threads')
    op.drop_table('threads')
    op.drop_table('persons')
    # ### end Alembic commands ###
